name: variable-demo

on:
  workflow_dispatch:
env:
  user_name: "Jacob"
  demo_name: "Variable Demo"
  
jobs:
  variableUsageJob:
    runs-on: ubuntu-latest
    env:
      job_var1: "job variable value"
    steps:
      - name: Using Workflow Variables
        env: 
          step_var1: "step variable value"
        run: echo Hello, $user_name! 
             Welcome to $demo_name, 
             here is job var1 $job_var1 
             here is step var1 $step_var1
      - name: Set user_name Variable
        run: echo "::set-env name=user_name::UpdatedName"
      - name: Set new_var Variable
        run: echo "::set-env name=new_var::newvaravlue"
      - name: Using Variables
        run: echo Hello, $user_name!
             Welcome to $demo_name!!!
             here is job var1 $job_var1
             here is new_var $new_var
